apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-montreal-hpa
  namespace: green-cloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-montreal
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: External
    external:
      metric:
        name: pubsub.googleapis.com|subscription|num_undelivered_messages
        selector:
          matchLabels:
            resource.labels.subscription_id: montreal-jobs-sub
      target:
        type: AverageValue
        averageValue: "20"
