apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  namespace: green-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      serviceAccountName: green-cloud-sa
      containers:
      - name: admission-controller
        image: asia-south1-docker.pkg.dev/green-cloud-pipeline-v2/green-cloud-pipeline/admission-controller:latest
        env:
        - name: PROJECT_ID
          value: "green-cloud-pipeline-v2"
        - name: ADMISSION_MODE
          value: "baseline"
        - name: SCALING_MODE
          value: "reactive"
        - name: CARBON_FORECASTER_URL
          value: "http://carbon-forecaster:8080/carbon"
        - name: CARBON_CACHE_TTL
          value: "60"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: admission-controller
  namespace: green-cloud
spec:
  selector:
    app: admission-controller
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
